---
- name: Prepare the dockers to run the tests
  hosts: all
  tasks:
    - name: Install packages
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - apt-transport-https

- name: Add deb repository with a gpg key from an url
  hosts: all
  vars:
    repository:
      url: https://apt.syncthing.net/
      options: syncthing stable
    gpg_key:
      key_url: https://syncthing.net/release-key.txt
  roles:
    - role: add-deb-repo

- name: Add deb repository with a gpg key from a repository
  hosts: all
  vars:
    repository:
      url: "http://repo.mongodb.org/apt/{{ ansible_distribution | lower }} trusty/mongodb-org/3.4"
      options: multiverse
    gpg_key:
      repository_url: hkp://keyserver.ubuntu.com
      id: 0C49F3730359A14518585931BC711F9BA15703C6
  roles:
    - role: add-deb-repo
